### ISSUE TITLE
Reactive Property on Inspector

### ISSUE THREAD

**Issue by alijaya** [TheWalruzz/godot-sx#3]
Is there anyway to make Reactive Property available on Inspector?

**Comment by TheWalruzz** [comment]
Currently no, I never looked into a way to make this work with `@export`. I might take a shot at it in the future, if that's really possible

**Comment by TheWalruzz** [comment]
Just tried some things and I believe it won't be possible without significant refactor of SxProperty/this whole library. Godot's `@export` annotation would work only with built-in types, nodes and resources, but SxProperty is inheriting `RefCounted` which cannot be exported in inspector even with a custom inspector plugin. This is not possible, unless I rewrite this library to a GDExtension, which I'm not planning to do anytime soon.

As for now, you can do something like this:

```gdscript
@export var initial_value: int
@onready var value_property: SxProperty = SxProperty.new(initial_value)
```

**Comment by alijaya** [comment]
> Just tried some things and I believe it won't be possible without significant refactor of SxProperty/this whole library. Godot's `@export` annotation would work only with built-in types, nodes and resources, but SxProperty is inheriting `RefCounted` which cannot be exported in inspector even with a custom inspector plugin. This is not possible, unless I rewrite this library to a GDExtension, which I'm not planning to do anytime soon.
> 
> As for now, you can do something like this:
> 
> ```gdscript
> @export var initial_value: int
> @onready var value_property: SxProperty = SxProperty.new(initial_value)
> ```

Ah yes, understood, this is acceptable solution for now...

**Comment by alijaya** [comment]
I've working on some workaround on this stuff... it's not pretty but, it somehow works...

This is a helper class
```GDScript
extends RefCounted
class_name SxHelper

static func helper_set(obj, property, value):
	if property.begins_with("sx_"): return false # forbid set sx_varName directly
	var res = obj.get("sx_" + property) # get the reactive property
	if res is SxProperty:
		res.value = value # set ".value" if it's SxProperty
		return true
	return false

static func helper_get(obj, property):
	if property.begins_with("sx_"): return null # if get sx_varName, use default handler (returning null)
	elif property.begins_with("s_"): # shortcut to get the signal
		var res = obj.get("sx_" + property.trim_prefix("s_")) # get the reactive property
		if res is SxProperty: return res.as_signal()
	else:
		var res = obj.get("sx_" + property) # get the reactive property
		if res is SxProperty: return res.value # if it's SxProperty, returning .value
	return null
	
static func helper_property_can_revert(obj, property):
	if property.begins_with("sx_"): return false
	return obj.get("sx_" + property) is SxProperty

static func helper_property_get_revert(obj, property):
	if property.begins_with("sx_"): return null
	var res = obj.get("sx_" + property)
	if res is SxProperty: return res.initial_value
	return null

static var _hasCalledGetPropertyList := false
static func helper_get_property_list(obj):
	if _hasCalledGetPropertyList: return []
	_hasCalledGetPropertyList = true
	var result = obj.get_property_list() \
	.filter(func (prop): return prop.name.begins_with("sx_")) \
	.map(func (prop):
		var sx = obj.get(prop.name)
		var propName = prop.name.trim_prefix("sx_")
		return {
			name = propName,
			type = typeof(sx.initial_value)
		}
	)
	_hasCalledGetPropertyList = false
	return result
```

Basically I intercept the _get, _set of the properties
```GDSCript
@tool
extends Node2D
class_name SxNode2D

func _get(property): return SxHelper.helper_get(self, property)
func _set(property, value): return SxHelper.helper_set(self, property, value)
func _property_can_revert(property): return SxHelper.helper_property_can_revert(self, property)
func _property_get_revert(property): return SxHelper.helper_property_get_revert(self, property)
func _get_property_list(): return SxHelper.helper_get_property_list(self)
```

Then I could use it like this
```GDScript
@tool
extends SxNode2D

var sx_testInt := SxProperty.new(10) # prefix with sx_ to declare reactive property, this will show in inspector

# Called when the node enters the scene tree for the first time.
func _ready():
	if Engine.is_editor_hint(): return
	
	self.s_testInt.subscribe(func(value: int): print(value)) # to access the signal, use s_varName, it's same as sx_varName.as_signal()
	self.testInt = 20 # to access the value, use varName directly, it's same as sx_varName.value
```

So if I subclass SxNode2D, and if I create variable with prefix "sx_", I could access the value without including "sx_" prefix.
But if I access internally, I should use "self.", because it needs to trigger the getter and setter.
And yes, with this way, you will lose the type-check.

**Comment by TheWalruzz** [comment]
Nice that you got something that works for you! Hopefully, there will be some improvement on Godot's side in the future that will make it possible to do it the clean way, so it can be properly implemented in this library.
